# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcu_sigma_cmle_cpp <- function(theta, tol) {
    .Call('_MIRT4FC_calcu_sigma_cmle_cpp', PACKAGE = 'MIRT4FC', theta, tol)
}

